### ISSUE TITLE
The Old SBEP Entities

### ISSUE THREAD

**Issue by David-Ralphsky** [SnakeSVx/spacebuild#78]
I think this is the right place to ask.

So back in 2009 we had these nifty weapon entities that used the Slyfo props, such as missile launchers, AA-guns, pulse weapons, etc. Unfortunately, they've also been broken since 2009.

So I've been fixing them for a couple days now, and it's in a very working state. Anyways, I'm asking permission to put it on the workshop, since you you guys are kind of the rightful owners and asking permission seems like the thing to do. If you say yes/I don't get a response, I'll upload it with a note saying "Created by the Spacebuild team" and take no credit and such. I just want to revive these old memories of spawnkilling with a gattling gun!

**Comment by X-Coder** [comment]
Hi David, a year ago the license was changed to make it workshop compatible. SBEP and Spacebuild 3 are both in Venom's workshop.

The weapons were originally part of SBEP_Weapons addon. For workshop and its size limit (~65MB) I think it would be a good idea if you could keep it a separate addon (weapons only).

Also it would be a good idea if you could put your fixes back into github, so we can improve / fix it further and keep it alive, or maybe SnakeSVx can merge it one day back into a new repository to keep the code together in one place. Linux support has to be tested too because it is case-sensitive on filenames.

I also fixed most of the weapons a while ago and tested them on my server, I run into small issues with some of the weapons: when I do lots of shooting sometimes the world breaks and everything gets invisible, maybe its just a general garrysmod bug or I messed something up. I think it was the small green plasma weapon shooting purple bullets. You can test my weapon fixes on my server.

If you put it on github, we can work together and I can add my fixes too.

**Comment by generalwrex** [comment]
if you can clone sbep, and merge your weapons changes with a pull request that would be great ;) 

For now I'm closing this issue as this is the Spacebuild issue tracker, not sbep xD
